<?php

use Illuminate\Database\Seeder;
use App\Models\Patologia;
class PatologiaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        //triaje
        Patologia::firstOrCreate(
            [
                "nombre"=>"Alergias",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );

        Patologia::firstOrCreate(
            [
                "nombre"=>"Diabetes",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );

        Patologia::firstOrCreate(
            [
                "nombre"=>"Asma",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"TBC",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Respiratorio",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Cardiovascular",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Reumatismo",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Cáncer",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Alcoholismo",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Hiperlipidemia",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"ACV/DCV",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"DM",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"HTA",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Dislipidemia",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"CBT",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Cardiopatía",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Otros cánceres",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Otras enfermedades",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Cáncer de mama",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>1
            ]
        );
        //oftalmo
        Patologia::firstOrCreate(
            [
                "nombre"=>"Alergias",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );

        Patologia::firstOrCreate(
            [
                "nombre"=>"Diabetes",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );

        Patologia::firstOrCreate(
            [
                "nombre"=>"Asma",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"TBC",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Respiratorio",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Cardiovascular",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Reumatismo",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Cáncer",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Alcoholismo",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Hiperlipidemia",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"ACV/DCV",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"DM",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"HTA",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Dislipidemia",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"CBT",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Cardiopatía",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Otros cánceres",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Otras enfermedades",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Cáncer de mama",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );

        //para otros de oftamologia -> antecedentes
        Patologia::firstOrCreate(
            [
                "nombre"=>"Diabetes M.",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Enf. Tiroides",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
        Patologia::firstOrCreate(
            [
                "nombre"=>"Otros",
                "estado_registro"=>"SU",
                "tipo_patologia_id"=>2
            ]
        );
    }
}
